import Head from "next/head";

import Layout from "../../components/layout";

import styles from "./first-post.module.scss";

export default function FirstPost(props: any) {
  return (
    <div className={styles.app}>
      <Head>
        <title>First Post - Hello Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className={styles.container}>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse rhoncus lacus et
            ligula porttitor, a ornare augue pellentesque. Pellentesque habitant morbi tristique
            senectus et netus et malesuada fames ac turpis egestas. Maecenas sollicitudin tempor
            neque in finibus. Praesent rutrum consectetur dolor at facilisis. Vestibulum lacinia
            velit at luctus ullamcorper. Curabitur maximus dolor quam, sed feugiat tellus ultrices
            eget. Curabitur ac pulvinar velit, id feugiat diam. Phasellus sollicitudin massa vel
            mauris blandit, ut faucibus nisl tempor. Ut dapibus felis ut arcu gravida mattis.
            Quisque rhoncus faucibus neque, nec vehicula mi imperdiet nec.
          </p>
          <p>
            Suspendisse elementum lectus ornare, viverra felis et, hendrerit leo. Donec porta semper
            ex nec sodales. Proin fringilla mi purus, nec dapibus ante luctus at. Donec magna neque,
            vulputate sit amet ultrices ut, ornare quis felis. Aliquam vehicula tortor mauris, vitae
            interdum arcu euismod et. Praesent faucibus magna ut orci ultricies faucibus. Mauris
            egestas mattis lectus vitae volutpat. Donec molestie ligula neque. Quisque dui diam,
            venenatis eget risus ac, porta fringilla nulla. Nullam venenatis tellus ut placerat
            convallis. Aenean rhoncus aliquet lacus, quis dictum tellus dignissim vel. Ut at orci
            non nisl facilisis convallis. Quisque faucibus malesuada euismod. Ut vulputate, odio et
            auctor porta, eros eros lacinia augue, eu sagittis risus est ut turpis. Nunc posuere
            tincidunt tellus a pharetra. Fusce et finibus eros, at facilisis augue.
          </p>
          <p>
            In lobortis eu orci sit amet ultrices. Duis ante dui, convallis vel lacus a, interdum
            porta sapien. Maecenas ex quam, pellentesque tincidunt turpis eget, pulvinar mollis
            orci. Pellentesque sit amet enim ut nunc lobortis mollis. Etiam sapien tortor, tincidunt
            ac quam volutpat, porttitor maximus quam. Donec vitae lectus vestibulum, sodales tellus
            pulvinar, condimentum orci. Sed interdum risus vitae malesuada molestie. Pellentesque
            interdum turpis quam, eu rutrum est posuere quis. Vivamus venenatis in ex vel viverra.
            Cras est elit, facilisis eget dolor ac, ultrices posuere risus. Duis at rhoncus sem.
            Maecenas non leo maximus, pretium tellus sed, elementum neque. Aliquam consectetur ex eu
            urna dapibus malesuada. Maecenas posuere, orci nec euismod congue, justo dolor euismod
            nisi, nec commodo sem urna vitae velit.
          </p>
          <p>
            Vestibulum rutrum augue nisi, a condimentum nisi semper quis. Vivamus vitae ullamcorper
            ipsum. Morbi id tortor ullamcorper, pellentesque dolor ut, tincidunt turpis. In
            vestibulum risus vitae vehicula dignissim. Pellentesque lobortis elit nisi, porttitor
            pretium ipsum accumsan ac. Praesent ultrices enim ornare, placerat leo condimentum,
            porttitor est. Proin suscipit sem arcu, suscipit fringilla nisl gravida nec. Proin at
            nisl fringilla, dictum lorem et, tempor tellus. Vivamus pharetra lectus risus, eget
            molestie elit dictum vitae. Vivamus sed purus eget urna laoreet tempor nec et odio.
          </p>
          <p>
            Maecenas convallis erat justo, nec sodales lorem posuere sit amet. Morbi placerat sit
            amet leo et dictum. Donec at lacus urna. Donec pellentesque sit amet mi at euismod.
            Mauris consequat ex ac nunc convallis lobortis vitae in tortor. Phasellus ut lectus
            nibh. Suspendisse tempus imperdiet lectus. Donec vehicula, ligula quis tristique
            fermentum, sem nisi luctus ipsum, vel imperdiet nunc velit in lectus.
          </p>
        </div>
      </Layout>
    </div>
  );
}
