import type { NextPage } from "next";
import Head from "next/head";

import Layout from "../components/layout";

const Home: NextPage = () => {
  const styles = (theme: any) => {
    [":hover"];
  };

  return (
    <div className="app">
      <Head>
        <title>Hello Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div
          style={{
            minWidth: "280px",
            width: "30%",
            transform: "scale(1.0)",
            height: "32rem",
            background: "rgba(128, 128, 255, 0.65)",
            backdropFilter: "blur(14px)",
            borderRadius: "1rem",
            margin: "1rem auto",
            zIndex: 99,
          }}
        ></div>
      </Layout>
    </div>
  );
};

export default Home;
